apiVersion: hub.kalypso.io/v1alpha1
kind: DeploymentDescriptor
metadata:
  name: kalypso-app-src-prod-functional-test
spec:
  workload:
    name: hello
    source:
        repo: https://github.com/kaizentm/kalypso-app-src
        branch: main
        path: .
    application:
        name: greeting
        workspace:
            name: kaizentm
  deploymentTarget:
    name: functional-test
    environment: prod
    manifests:
        repo: https://github.com/kaizentm/kalypso-app-gitops
        branch: prod
        path: functional-test
  workloadVersion:
    version: 0.0.1-31
    commit: 65b56880a770e2e143c1b9fb7be23045ecc10aed